# yaml-language-server: $schema=https://raw.githubusercontent.com/microsoft/azure-pipelines-vscode/main/service-schema.json
name: 0.0$(Rev:.r)

trigger:
  batch: "true"
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

stages:
  - stage: Build
    jobs:
      - template: pipeline/wakeup.yml
      - template: pipeline/build.yml

  - stage: Test
    condition: and(succeeded(), eq(variables['build.sourceBranchName'], 'main'))
    variables:
      - group: "Azure shared resource credentials (Test)"
      - name: EnvironmentConfigurationLabel
        value: test

    jobs:
      - template: pipeline/wakeup.yml
      - deployment: Deployment
        environment: Test (West Europe)
        pool:
          name: Private Linux
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current

                - template: pipeline/deploy.yml
                  parameters:
                    environmentLowerCaseName: ${{ variables.EnvironmentConfigurationLabel }}

  - stage: Production
    condition: and(succeeded(), eq(variables['build.sourceBranchName'], 'main'))
    variables:
      - group: "Azure shared resource credentials (Production)"
      - name: EnvironmentConfigurationLabel
        value: production

    jobs:
      - template: pipeline/wakeup.yml
      - deployment: Deployment
        environment: Production (West Europe)
        pool:
          name: Private Linux
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current

                - template: pipeline/deploy.yml
                  parameters:
                    environmentLowerCaseName: ${{ variables.EnvironmentConfigurationLabel }}
