# yaml-language-server: $schema=https://raw.githubusercontent.com/microsoft/azure-pipelines-vscode/main/service-schema.json
jobs:
  - job: BuildOnLinux
    pool:
      name: Private Linux
    workspace:
      clean: all

    steps:
      - download: none

      - task: Npm@1
        displayName: npm ci (install)
        inputs:
          command: ci

      - task: Npm@1
        displayName: "npm run typecheck"
        inputs:
          command: "custom"
          customCommand: "run typecheck"

      - task: Npm@1
        displayName: "npm run lint"
        inputs:
          command: "custom"
          customCommand: "run lint"

      - task: Npm@1
        displayName: "npm run test:ci"
        continueOnError: true
        inputs:
          command: "custom"
          customCommand: "run test:ci"

      - task: PublishTestResults@2
        displayName: "Publish unit test results"
        inputs:
          testResultsFormat: "JUnit"
          testResultsFiles: "test-results.xml"
          failTaskOnFailedTests: true

      - template: build-targeting-environment.yml
        parameters:
          targetEnvironmentNameLowerCase: test

      - template: build-targeting-environment.yml
        parameters:
          targetEnvironmentNameLowerCase: production
